### ISSUE TITLE
NoSuchMethodError: The getter 'value' was called on null.

### ISSUE THREAD

**Issue by mehrdad-shokri** [LanarsInc/animated-bottom-navigation-bar-flutter#1]
````
════════ Exception caught by widgets library ════════════════
The following NoSuchMethodError was thrown building AnimatedBottomNavigationBar(dirty, dependencies: [_ScaffoldScope, _EffectiveTickerMode], state: _AnimatedBottomNavigationBarState#a9a1c):
The getter 'value' was called on null.
Receiver: null
Tried calling: value
````

``pubsepc.yaml``
``  animated_bottom_navigation_bar: 0.1.2+2``

``home.dart``:
````
Scaffload(
   ...
    bottomNavigationBar: AnimatedBottomNavigationBar(
        icons: [Icons.brightness_5, Icons.brightness_4],
        activeIndex: _bottomNavigationIndex,
        gapLocation: GapLocation.center,
        notchSmoothness: NotchSmoothness.verySmoothEdge,
        leftCornerRadius: 32,
        rightCornerRadius: 32,
        onTap: (index) => setState(() => _bottomNavigationIndex = index),
        //other params
      )
);
````

It's this line: 
``width: widget.gapWidth * widget.notchAndCornersAnimation.value,`` line 212 ``animated_bottom_navigation_bar.dart``

**Comment by nkenna** [comment]
ANy solution to this?

**Comment by mehrdad-shokri** [comment]
@nkenna refer to the [example](https://github.com/LanarsInc/animated-bottom-navigation-bar-flutter/blob/master/example/lib/main.dart) you need to provide ``notchAndCornersAnimation`` argument to the ``AnimatedBottomNavigationBar``

**Comment by TimilehinEmmanuelOJO** [comment]
> @nkenna refer to the [example](https://github.com/LanarsInc/animated-bottom-navigation-bar-flutter/blob/master/example/lib/main.dart) you need to provide `notchAndCornersAnimation` argument to the `AnimatedBottomNavigationBar`

i have done this but still experiencing the same error

**Comment by doppio** [comment]
The README doesn't mention this parameter and the internal documentation describes it as optional. Does the documentation need to be updated or should it actually be optional?

**Comment by mehrdad-shokri** [comment]
@doppio previously I read the source code it calls this member value and does not initialize anywhere by itself so I guess README should be updated

**Comment by LuizFilipeMedeira** [comment]
Esse problema esta corrigido no meu fork.
 Add to pubspec.yaml:
animated_bottom_navigation_bar:
    git:
      url: https://github.com/LuizFilipeMedeira/animated-bottom-navigation-bar-flutter
      ref: master

**Comment by realdiganta** [comment]
Add this bit of code in your initState and the error will go away:


final systemTheme = SystemUiOverlayStyle.light.copyWith(
      systemNavigationBarColor: Colors.black,
      systemNavigationBarIconBrightness: Brightness.light,
    );
    SystemChrome.setSystemUIOverlayStyle(systemTheme);

**Comment by yash-dxt** [comment]
I'm getting the same issue but on line 236.
This happens when I put:
`        gapLocation: GapLocation.end
`
Also, I'm using a floating action button here.

**Comment by is10vmust** [comment]
Same here , any one have a solution

**Comment by is10vmust** [comment]
> Esse problema esta corrigido no meu fork.
> Add to pubspec.yaml:
> animated_bottom_navigation_bar:
> git:
> url: https://github.com/LuizFilipeMedeira/animated-bottom-navigation-bar-flutter
> ref: master

Thats worked with me @LuizFilipeMedeira Thanks
