### ISSUE TITLE
How to add text for every option?

### ISSUE THREAD

**Issue by hizmarck** [LanarsInc/animated-bottom-navigation-bar-flutter#11]
I've struggled to understand the way to add text on every option like this image (brightness 0, brightness 1...):

![image](https://user-images.githubusercontent.com/4828196/104640082-c7e48b80-566d-11eb-9bab-c0c7a498c3a8.png)

**Comment by Vizhan** [comment]
@hizmarck 
See [example](https://pub.dev/packages/animated_bottom_navigation_bar/example)

**Comment by hizmarck** [comment]
Thanks for your soon support, thanks.
