### ISSUE TITLE
Bottom navigation bar color

### ISSUE THREAD

**Issue by ahmed2hamy** [LanarsInc/animated-bottom-navigation-bar-flutter#12]
How can I change this color to be transparent in front of the view ?

![IMG_20210219_185348](https://user-images.githubusercontent.com/35851365/108535638-39a29b80-72e4-11eb-9840-a6f0e6bbe7d1.jpg)

**Comment by Vizhan** [comment]
@ahmed2hamy You need to add `extendBody: true` in `Scaffold` widget.
See [example](https://pub.dev/packages/animated_bottom_navigation_bar/example)
```
 @override
  Widget build(BuildContext context) {
    return Scaffold(
      extendBody: true,
      ....
```

**Comment by Vizhan** [comment]
@ahmed2hamy Did that help?

**Comment by Vizhan** [comment]
I'm going to close it for now. Feel free to reopen if needed.

**Comment by ahmed2hamy** [comment]
Yes it worked, Thanks for the help and sorry for the late response.
