### ISSUE TITLE
Doesn't work on release mode on Android 11

### ISSUE THREAD

**Issue by xirainfotech** [LanarsInc/animated-bottom-navigation-bar-flutter#14]
CODE:
return Scaffold(
          body: _pages[_nav.getIndex()],
          drawer: CustomDrawer(),
          floatingActionButton: FloatingActionButton(
            onPressed: () {
              Get.toNamed(Routes.CARTPAGE);
            },
          ),
          floatingActionButtonLocation:
              FloatingActionButtonLocation.centerDocked,
          bottomNavigationBar: AnimatedBottomNavigationBar(
            icons: _iconList,
            splashColor: accentColor,
            activeColor: accentColor,
            inactiveColor: Colors.black.withOpacity(0.5),
            notchMargin: 10.0,
            activeIndex: _nav.getIndex(),
            gapLocation: GapLocation.center,
            leftCornerRadius: 32,
            rightCornerRadius: 32,
            notchSmoothness: NotchSmoothness.verySmoothEdge,
            onTap: (val) {
              _nav.changeIndex(val);
            },
          ),
        );

ERROR: 
Wrong gap location in AnimatedBottomNavigationBar towards FloatingActionButtonLocation => consider use GapLocation.end instead of GapLocation.center or change FloatingActionButtonLocation
The relevant error-causing widget was
AnimatedBottomNavigationBar

**Comment by vizhan-lanars** [comment]
Can't reproduce with the code snippet. (Tested Pixel 3a XL, Android 11,  release)
Could you provide a minimum project with the issue?

**Comment by xirainfotech** [comment]
Ive used that code in this app: https://play.google.com/store/apps/details?id=com.xira.mymk
Check if its working for you or not... 
Its not working only on Android 11

**Comment by vizhan-lanars** [comment]
It is working fine for me.

**Comment by vizhan-lanars** [comment]
![photo_2021-03-17 11 24 56](https://user-images.githubusercontent.com/54840855/111444847-7a3eda80-8713-11eb-9ab1-6214b4c63ebb.jpeg)

**Comment by xirainfotech** [comment]
Thanks for your reply, I'll test my code and check on few more devices

**Comment by xirainfotech** [comment]
Closing this issue for now
