### ISSUE TITLE
Null safety enhancement

### ISSUE THREAD

**Issue by mimarko** [LanarsInc/animated-bottom-navigation-bar-flutter#15]
Please migrate to null safety.

**Comment by leynier** [comment]
Any update about this guys? I could help with this.

**Comment by leynier** [comment]
https://dart.dev/null-safety/migration-guide

**Comment by vizhan-lanars** [comment]
Hi there!
Currently, we don't have time for that. But definitely, we'll migrate to null safety.
BTW, PR are welcome )
Sorry for the late response.

**Comment by vizhan-lanars** [comment]
MIgrated in version 0.3.0.
