### ISSUE TITLE
error happened when i migrated to flutter 2

### ISSUE THREAD

**Issue by mostafa3bdelkader** [LanarsInc/animated-bottom-navigation-bar-flutter#16]
**when i migrated to flutter 2 this error appears before that all was well.**

============================================
The following _CastError was thrown during paint():
type 'Null' is not a subtype of type 'Offset' in type cast

The relevant error-causing widget was: 
  AnimatedBottomNavigationBar file:///Users/alexapps/AndroidStudioProjects/n8/lib/Widgets/bottom_navigation_bar.dart:103:56
When the exception was thrown, this was the stack: 
#0      List.length= (dart:core-patch/growable_array.dart:222:12)
#1      CircularNotchedAndCorneredRectangle.getOuterPath (package:animated_bottom_navigation_bar/src/circular_notched_and_cornered_shape.dart:108:26)
#2      CircularNotchedAndCorneredRectangleClipper.getClip (package:animated_bottom_navigation_bar/src/circular_notch_and_corner_clipper.dart:30:18)
#3      _RenderCustomClip._updateClip (package:flutter/src/rendering/proxy_box.dart:1377:25)
#4      RenderPhysicalShape.paint (package:flutter/src/rendering/proxy_box.dart:1998:7)
...
The following RenderObject was being processed when the exception was fired: RenderPhysicalShape#4430a relayoutBoundary=up1
...  needs compositing
...  parentData: offset=Offset(0.0, 725.1); id=_ScaffoldSlot.bottomNavigationBar (can use size)
...  constraints: BoxConstraints(w=392.7, 0.0<=h<=781.1)
...  size: Size(392.7, 56.0)
...  elevation: 8.0
...  color: Color(0x00000000)
...  shadowColor: Color(0x00000000)
...  clipper: CircularNotchedAndCorneredRectangleClipper
RenderObject: RenderPhysicalShape#4430a relayoutBoundary=up1
  needs compositing
  parentData: offset=Offset(0.0, 725.1); id=_ScaffoldSlot.bottomNavigationBar (can use size)
  constraints: BoxConstraints(w=392.7, 0.0<=h<=781.1)
  size: Size(392.7, 56.0)
  elevation: 8.0
  color: Color(0x00000000)
  shadowColor: Color(0x00000000)
  clipper: CircularNotchedAndCorneredRectangleClipper
...  child: RenderPhysicalModel#6b7a5 relayoutBoundary=up2 NEEDS-PAINT
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=392.7, 0.0<=h<=781.1)
...    size: Size(392.7, 56.0)
...    elevation: 0.0
...    color: Color(0xffffffff)
...    shadowColor: Color(0xffffffff)
...    shape: BoxShape.rectangle
...    borderRadius: BorderRadius.zero
...    child: _RenderInkFeatures#1ea29 relayoutBoundary=up3 NEEDS-PAINT
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=392.7, 0.0<=h<=781.1)
...      size: Size(392.7, 56.0)
...      child: RenderPadding#8864b relayoutBoundary=up4 NEEDS-PAINT
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=392.7, 0.0<=h<=781.1)
...        size: Size(392.7, 56.0)
...        padding: EdgeInsets.zero
...        textDirection: ltr
...        child: RenderConstrainedBox#7bfe7 relayoutBoundary=up5 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(w=392.7, 0.0<=h<=781.1)
...          size: Size(392.7, 56.0)
...          additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=56.0)
====================================================================================================

**Comment by vizhan-lanars** [comment]
Did you try `flutter clean` ?

**Comment by mostafa3bdelkader** [comment]
yes many times and also invalidate caches.

**Comment by vizhan-lanars** [comment]
Could you provide `flutter doctor` info?

**Comment by mostafa3bdelkader** [comment]
Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en)
    • Flutter version 2.0.3 at /Users/alexapps/tools/flutter
    • Framework revision 4d7946a68d (4 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

**Comment by vizhan-lanars** [comment]
Is there an option for you to provide a minimum code snippet to reproduce that issue?

**Comment by mostafa3bdelkader** [comment]
import 'dart:async';
import 'package:animated_bottom_navigation_bar/animated_bottom_navigation_bar.dart';
import 'package:auto_size_text/auto_size_text.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:n8/Screens/contacts_screen.dart';
import 'package:n8/Screens/qrcode_screen.dart';

import 'package:n8/Screens/settings_screen.dart';

import '../Screens/main_screen.dart';

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {
  final autoSizeGroup = AutoSizeGroup();

  late AnimationController _animationController;
  Animation<double>? animation;
  late CurvedAnimation curve;
  PageController _pageController = PageController();
  int currentTab = 0;

  final iconList = <IconData>[
    FontAwesomeIcons.userAlt,
    FontAwesomeIcons.users,
    FontAwesomeIcons.qrcode,
    FontAwesomeIcons.slidersH
  ];

  final iconTitles = <String>['Profile', 'Contacts', 'Scan QR', 'Settings'];

  List<Widget> _screens = [
    MainScreen(),
    ContactsScreen(),
    QrCodeScreen(),
    SettingScreen()
  ];

  void _onItemTapped(int selectedIndex) {
    _pageController.jumpToPage(selectedIndex);
  }

  @override
  void initState() {
    super.initState();
    final systemTheme = SystemUiOverlayStyle.light.copyWith(
      systemNavigationBarColor: Colors.white,
      systemNavigationBarIconBrightness: Brightness.dark,
    );
    SystemChrome.setSystemUIOverlayStyle(systemTheme);

    _animationController = AnimationController(
      duration: Duration(seconds: 1),
      vsync: this,
    );
    curve = CurvedAnimation(
      parent: _animationController,
      curve: Interval(
        0.5,
        1.0,
        curve: Curves.fastOutSlowIn,
      ),
    );
    animation = Tween<double>(
      begin: 0,
      end: 1,
    ).animate(curve);

    Future.delayed(
      Duration(seconds: 1),
      () => _animationController.forward(),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageView(
        controller: _pageController,
        children: _screens,
        onPageChanged: (index) {
          setState(() {
            currentTab = index;
          });
        },
        physics: NeverScrollableScrollPhysics(),
      ),
      floatingActionButton: ScaleTransition(
        scale: animation!,
        child: FloatingActionButton(
          elevation: 8,
          backgroundColor: Colors.white,
          child: Image.asset('assets/images/scanQR.png'),
          onPressed: () {},
        ),
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      bottomNavigationBar: AnimatedBottomNavigationBar.builder(
        itemCount: iconList.length,
        tabBuilder: (int index, bool isActive) {
          final color = isActive ? Colors.blue : Colors.grey;
          return Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(
                iconList[index],
                size: 24,
                color: color,
              ),
              const SizedBox(height: 4),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 8),
                child: AutoSizeText(
                  iconTitles[index],
                  maxLines: 1,
                  style: TextStyle(color: color),
                  group: autoSizeGroup,
                ),
              )
            ],
          );
        },
        backgroundColor: Colors.white,
        activeIndex: currentTab,
        splashColor: Colors.blue,
        notchAndCornersAnimation: animation,
        splashSpeedInMilliseconds: 300,
        notchSmoothness: NotchSmoothness.defaultEdge,
        gapLocation: GapLocation.center,
        leftCornerRadius: 32,
        rightCornerRadius: 32,
        onTap: (index) => setState(() => this._onItemTapped(index)),
      ),
    );
  }
}

**Comment by vizhan-lanars** [comment]
Got it. Thank you. 
I've just fixed that locally. Need some tests.
Will deploy fix asap )

**Comment by vizhan-lanars** [comment]
Fixed in version 0.3.2.
