### ISSUE TITLE
How to make the bg color transparent 

### ISSUE THREAD

**Issue by rashmisridar** [LanarsInc/animated-bottom-navigation-bar-flutter#18]
How to make the bg color transparent 
![WhatsApp Image 2021-05-12 at 5 07 10 PM (1)](https://user-images.githubusercontent.com/8536749/117969160-b160ef00-b344-11eb-953f-b0219beb8a44.jpeg)

**Comment by vizhan-lanars** [comment]
@rashmisridar I guess you need this:
```
 Scaffold(
        extendBody: true,
         ...
 ). 
```
 
 Take a look [example](https://pub.dev/packages/animated_bottom_navigation_bar/example)

**Comment by rashmisridar** [comment]
@vizhan-lanars Issue resolved. Thank you

**Comment by rashmisridar** [comment]
@vizhan-lanars When `extendBody: true`. Then getting this error from nested scroll view (not for static data, while retrieving the data from firebase/async ). Any idea on this ? Thanks.

 https://stackoverflow.com/questions/58339739/nestedscrollview-issue-throwing-error-when-switching-between-two-screens
