### ISSUE TITLE
How to change status bar color and navigation bar color in ios 

### ISSUE THREAD

**Issue by rashmisridar** [LanarsInc/animated-bottom-navigation-bar-flutter#20]
After adding SafeArea as the top of the widget how to change the status bar color and navigation bat color

**Comment by vizhan-lanars** [comment]
Hello
Show me the code

**Comment by rashmisridar** [comment]
Ok Sure

**Comment by vizhan-lanars** [comment]
I suppose that the issue is not connected to the package.

**Comment by rashmisridar** [comment]
> I suppose that the issue is not connected to the package.

yes, you are right. Thanks.
