### ISSUE TITLE
any roadmap?

### ISSUE THREAD

**Issue by Macacoazul01** [LanarsInc/animated-bottom-navigation-bar-flutter#21]
Do you have any roadmap of updates planned for this library? 

if so, we users could help with the development

**Comment by vizhan-lanars** [comment]
Thank you for your interest in the plugin.
We have not had any roadmap yet.
We review requests for changes or improvements from users.

But any help welcome ))

**Comment by Macacoazul01** [comment]
There are some forks of this plugin with changes implemented. They could be implemented here too (maybe i can help you with this)

https://github.com/zae1403/animated-bottom-navigation-bar-flutter

https://github.com/xEyad/animated-bottom-navigation-bar-flutter

https://github.com/rashmisridar/animated-bottom-navigation-bar-flutter

https://github.com/ranianabil55/animated-bottom-navigation-bar-flutter

https://github.com/MostafaHossam4/animated-bottom-navigation-bar-flutter

https://github.com/mondoktamas/animated-bottom-navigation-bar-flutter

https://github.com/LuizFmdr/animated-bottom-navigation-bar-flutter

https://github.com/HTMHell/animated-bottom-navigation-bar-flutter

https://github.com/Halsean-Ventures-Private-Limited/animated-bottom-navigation-bar-flutter

https://github.com/franciscrispin/animated-bottom-navigation-bar-flutter

https://github.com/abbas-25/animated-bottom-navigation-bar-flutter

https://github.com/a-leblond/animated-bottom-navigation-bar-flutter

**Comment by vizhan-lanars** [comment]
Thanks
Need time to check the forks above.

**Comment by Abh1shekShinde** [comment]
is there anything i can help in contributing ... i really need to contribute to something.

**Comment by Macacoazul01** [comment]
@Abh1shekShinde maybe you could port some updates from the other forks

**Comment by Abh1shekShinde** [comment]
Can You pls provide more details ..I didn't understand

**Comment by Macacoazul01** [comment]
> There are some forks of this plugin with changes implemented. They could be implemented here too (maybe i can help you with this)
> 
> 
> 
> https://github.com/zae1403/animated-bottom-navigation-bar-flutter
> 
> 
> 
> https://github.com/xEyad/animated-bottom-navigation-bar-flutter
> 
> 
> 
> https://github.com/rashmisridar/animated-bottom-navigation-bar-flutter
> 
> 
> 
> https://github.com/ranianabil55/animated-bottom-navigation-bar-flutter
> 
> 
> 
> https://github.com/MostafaHossam4/animated-bottom-navigation-bar-flutter
> 
> 
> 
> https://github.com/mondoktamas/animated-bottom-navigation-bar-flutter
> 
> 
> 
> https://github.com/LuizFmdr/animated-bottom-navigation-bar-flutter
> 
> 
> 
> https://github.com/HTMHell/animated-bottom-navigation-bar-flutter
> 
> 
> 
> https://github.com/Halsean-Ventures-Private-Limited/animated-bottom-navigation-bar-flutter
> 
> 
> 
> https://github.com/franciscrispin/animated-bottom-navigation-bar-flutter
> 
> 
> 
> https://github.com/abbas-25/animated-bottom-navigation-bar-flutter
> 
> 
> 
> https://github.com/a-leblond/animated-bottom-navigation-bar-flutter

.
