### ISSUE TITLE
Animated-bottom-navigation-bar-flutter MaterialRoute navigation

### ISSUE THREAD

**Issue by InfinityCoder88** [LanarsInc/animated-bottom-navigation-bar-flutter#24]
How to use animated-bottom-navigation-bar-flutter with MaterialRoute for navigation to other screens? I tried but unsuccessfully :(
It's possible, can you guys provide an example? Thanks in advance!

**Comment by vizhan-lanars** [comment]
Yes, it is (e.g. nested Navigator):
```
Scaffold(
     appBar: _buildFlowAppBar(),
     body: Navigator(
       key: _navigatorKey,
       initialRoute: widget.setupPageRoute,
       onGenerateRoute: _onGenerateRoute,
     ),
 );
```
https://flutter.dev/docs/cookbook/effects/nested-nav
