### ISSUE TITLE
Elevation Not Work Perfectly

### ISSUE THREAD

**Issue by yusriltakeuchi** [LanarsInc/animated-bottom-navigation-bar-flutter#25]
Hello, when i use this package, i use elevation with number 100, but the result still looks thin shadows.
i set elevation to 100, but nothing works.

<img width="418" alt="Screen Shot 2021-10-01 at 13 37 43" src="https://user-images.githubusercontent.com/10339660/135576414-63091970-f53e-4f0d-b70b-414dc5fe2c89.png">

**Comment by vizhan-lanars** [comment]
What do you expect from an elevation of 100? 
I see a barely noticeable shadow (it looks like a content screen background). That is normal behaviour. 

If you set elevation 0, your content screen will be total white.
If you set elevation 8, you will see a clear shadow.
