### ISSUE TITLE
with any change of active index automatically sets it self to 0 

### ISSUE THREAD

**Issue by Abraham-EH** [LanarsInc/animated-bottom-navigation-bar-flutter#28]
<img width="317" alt="Screen Shot 2021-11-07 at 2 01 30 AM" src="https://user-images.githubusercontent.com/50684349/140625604-2ad65e51-c712-412e-bb1f-ac2612a7b8ed.png">

**Comment by vizhan-lanars** [comment]
Didn't get you. It works flawlessly on my side.
You could inspect the example code.
