### ISSUE TITLE
Animation on the button.

### ISSUE THREAD

**Issue by fclauss72** [LanarsInc/animated-bottom-navigation-bar-flutter#29]
Every time I press a different menu button there is animation on the button itself. 
If, however, I repeat the same button, the animation does not work. 
Is there a way to run the animation even by pressing the same button again?
Thx.

**Comment by vizhan-lanars** [comment]
@fclauss72 
This is intended behaviour.
You could find that in the `animated_bottom_navigation_bar.dart` :
```
  @override
  void didUpdateWidget(AnimatedBottomNavigationBar oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.activeIndex != widget.activeIndex) {
      _startBubbleAnimation();
    }
  }
  ```
  You could fork to achieve what you want

**Comment by fclauss72** [comment]
Ok, thanks.
