### ISSUE TITLE
FAB animation resizes/distorts bottom

### ISSUE THREAD

**Issue by adrianvintu** [LanarsInc/animated-bottom-navigation-bar-flutter#33]
When pressing on the FAB, the bottom sheet gets distorted (the corners change, the autosize text as well). This looks very unappealing to me and I have never seen this behaviour before.
Is there any way to apply the scale animation but leave the bottom unchanged?

**Comment by adrianvintu** [comment]
I have removed the autotext and set fixed text size. The bottom no longer distorts. You can close this ticket.
Thank you for your amazing work!

**Comment by adrianvintu** [comment]
Sorry, removing the autotext did not fix it.

**Comment by vizhan-lanars** [comment]
Hi.
Could U attach a video of the issue and working code to reproduce that?

**Comment by adrianvintu** [comment]
It looks really bad. Is this intended?

[device-2022-05-19-151740.zip](https://github.com/LanarsInc/animated-bottom-navigation-bar-flutter/files/8728982/device-2022-05-19-151740.zip)

**Comment by vizhan-lanars** [comment]
Why is the device time on the video jump back and forth for 1 minute?

**Comment by adrianvintu** [comment]
Just the video encoding, I guess.

First recording is from emulator , this new one is from Samsung Galaxy S10.

[device-2022-05-19-154409.zip](https://github.com/LanarsInc/animated-bottom-navigation-bar-flutter/files/8729152/device-2022-05-19-154409.zip)

**Comment by vizhan-lanars** [comment]
Oh, I got U )
Yes, it's a showcase and an intended behaviour for pressing on the FAB to restart animation.
U could delete a `ScaleTransition` for the  `FloatingActionButton`
