### ISSUE TITLE
AnimatedBottomNavigationBar Icons as List<Widgets> instead of List<IconData>

### ISSUE THREAD

**Issue by xSuperMu** [LanarsInc/animated-bottom-navigation-bar-flutter#5]
This suggestion will add more flexibility to add custom widgets instead of only plain icons.
For example, 

A column that has an ImageAsset + Descriptive text.

<img width="775" alt="Screen Shot 2020-09-07 at 11 00 41 AM" src="https://user-images.githubusercontent.com/17935590/92369559-75142980-f0f9-11ea-981a-a4d10eaafc9e.png">

**Comment by mtkgeek** [comment]
I absolutely second this. Greater flexibility.

**Comment by vizhan-lanars** [comment]
@xSuperMu @mtkgeek 
New functionality is available in version 0.2.0.

**Comment by Nazacheres** [comment]
@vizhan-lanars actually it seems like it is not, maybe there is a regression in 0.2.1, but I see List<IconData> as a mandatory constructor parameter for AnimatedBottomNavigationBar.

**Comment by Vizhan** [comment]
@Nazacheres Did you check a new named constructor `AnimatedBottomNavigationBar.builder`?
Here is an [example](https://pub.dev/packages/animated_bottom_navigation_bar/example).
