### ISSUE TITLE
Add title in bottom bar

### ISSUE THREAD

**Issue by muhammadjalal** [LanarsInc/animated-bottom-navigation-bar-flutter#51]
some time it is difficult to recognize icons.  give option to add title with icons in bottom bar.
2. create 1 example with builder function for guidelines

**Comment by vizhan-lanars** [comment]
You are able to add title with icons (or more) using `AnimatedBottomNavigationBar.builder`.
There is an [example](https://pub.dev/packages/animated_bottom_navigation_bar/example) of usage
