### ISSUE TITLE
using safe area and extend body causes color issue

### ISSUE THREAD

**Issue by Bimbum1337** [LanarsInc/animated-bottom-navigation-bar-flutter#52]
Hello, I'm trying to turn this into transparent
![image](https://user-images.githubusercontent.com/113800085/222275501-2a8c32c3-5b5c-444c-bef9-30c0ab73f872.png)

I know that I have to extend the body to get it working, but the issue is am using safe area at the body, but seems that it doesn't work unless I remove the safearea widget

```
body: SafeArea(
              child: snapshot.data ?? _viewModel.mainScreenWidgets[0],
            ),
```

**Comment by MarkoshYevhenii** [comment]
@Bimbum1337 Try setting the maintainBottomViewPadding parameter to true for the SafeArea widget.
` SafeArea(
        maintainBottomViewPadding: true,
        child: ____ ,
      )`

**Comment by jonorozcoc** [comment]
I'm not using SafeArea component and the background issue persists

**Comment by baptistesx** [comment]
Hey,

i'm currently facing the same issue. How to set this white part transparent?

I tried your solution: Scaffold > body > SafeArea > maintainBottomViewPadding: true

but it's not working :s

**Comment by vizhan-lanars** [comment]
@MarkoshYevhenii

**Comment by baptistesx** [comment]
Awesome, it works thanks a lot !
