### ISSUE TITLE
Render Issues

### ISSUE THREAD

**Issue by raiesraj** [LanarsInc/animated-bottom-navigation-bar-flutter#57]
Why am not able to use right corner radius it is show a Error "**RightCorner Radius ALong With GapLocation and FAb.endDocked render issues ...** "
![isu](https://github.com/LanarsInc/animated-bottom-navigation-bar-flutter/assets/83076095/a0e82504-00b2-44b7-9aaa-bc78719042ec)

**Comment by vizhan-lanars** [comment]
Hi 
Show me the code

**Comment by vizhan-lanars** [comment]
It would be nice of you to provide executable code, not an image

**Comment by raiesraj** [comment]
Thank you For your response and time @vizhan-lanars
