### ISSUE TITLE
 Feature Request - Support for Icon Gradients

### ISSUE THREAD

**Issue by MoritzMessner** [LanarsInc/animated-bottom-navigation-bar-flutter#59]
Dear **animated-bottom-navigation-bar** package maintainers,

I hope this message finds you well. I am writing to request a new feature for the animated-bottom-navigation-bar-flutter package. Firstly, I want to express my appreciation for the work you've done in creating and maintaining this package, which has been a valuable addition to the Flutter community.

Problem:
Currently, when using animated-bottom-navigation-bar-flutter, I can only use a single color to highlight the icons in the navigation bar. While this is functional, it can be limiting in terms of design flexibility and creativity.

Request:
I kindly request that you consider implementing a feature that would allow users to use gradients for the icons in the navigation bar. This enhancement would greatly enhance the visual appeal and customization options for Flutter apps using this package.

Having the ability to apply gradients to navigation bar icons would enable developers to:

- Create more visually appealing and eye-catching navigation bars.
- Match the navigation bar style with the overall theme and design of their Flutter apps.
- Experiment with various gradient combinations to achieve unique and attractive UI effects.
- Stay in line with the latest design trends and provide a modern look to their apps.

I understand that adding this feature may require some development effort, but I believe it would greatly benefit the community and make the animated-bottom-navigation-bar-flutter package even more versatile and appealing to Flutter developers.

Thank you for your time and consideration of this request.

**Comment by vizhan-lanars** [comment]
Hi
Thanks for your request and kind feedback. We do really appreciate it.

Would `AnimatedBottomNavigationBar.builder` cover your needs? Please check [example](https://pub.dev/packages/animated_bottom_navigation_bar/example)

**Comment by MoritzMessner** [comment]
yes, it does! Thank you so much.

**Comment by vizhan-lanars** [comment]
You are welcome )

I think we should update README to make it clear with `AnimatedBottomNavigationBar.builder`
