### ISSUE TITLE
Adjust border around square FAB

### ISSUE THREAD

**Issue by DangTuCS** [LanarsInc/animated-bottom-navigation-bar-flutter#63]
![image](https://github.com/LanarsInc/animated-bottom-navigation-bar-flutter/assets/80461479/f9e7a791-c235-480d-99d4-044d71a811ea)
I don't want a bottom circular at the notch, how can I change to make like a square circular at the bottom of the notch.

**Comment by vizhan-lanars** [comment]
Hello
Rounded shapes for notch are not supported for now
