### ISSUE TITLE
it's not displaying menu correctly 

### ISSUE THREAD

**Issue by putrasurya** [LanarsInc/animated-bottom-navigation-bar-flutter#7]
i'm using version ^0.2.0

<img width="781" alt="image" src="https://user-images.githubusercontent.com/3635850/102285321-a7d78480-3f68-11eb-9714-31221eeb3d98.png">

**Comment by alexeylanars** [comment]
Hi there!

Could you provide full code for `AnimatedBottomNavigationBar` ?

**Comment by putrasurya** [comment]
that's all

**Comment by vizhan-lanars** [comment]
@putrasurya, could you show the whole Scaffold widget?

**Comment by vizhan-lanars** [comment]
In case when you don't use `Scaffold.floatingActionButton`, you have to set `gapLocation: GapLocation.none` for `AnimatedBottomNavigationBar`.
