### ISSUE TITLE
LateInitializationError: Field '_bubbleController@3976458843' has not been initialized，

### ISSUE THREAD

**Issue by leijingxing** [LanarsInc/animated-bottom-navigation-bar-flutter#70]
![image](https://github.com/LanarsInc/animated-bottom-navigation-bar-flutter/assets/35052117/692661ab-ea8a-4eca-bc3d-6078e538afd5)

**Comment by leijingxing** [comment]
After disposing the page and going to the login page, this error is reported.

**Comment by leijingxing** [comment]
animated_bottom_navigation_bar: ^1.3.2.   animated_bottom_navigation_bar: ^1.3.0 is ok.

**Comment by heshesh2010** [comment]
+1

**Comment by Clon1998** [comment]
Hey, I had a look at the code. The issue is thrown because the bubbleController is not present if the user never clicks any of the tabs.
#71 should fix it.

**Comment by parmarravi** [comment]
is there any fixed branch we could use?

**Comment by BaoTrung37** [comment]
is this bug already fixed?

**Comment by vizhan-lanars** [comment]
Yes
