### ISSUE TITLE
List View Scrolling Issue

### ISSUE THREAD

**Issue by fahalsalam** [LanarsInc/animated-bottom-navigation-bar-flutter#77]
https://github.com/LanarsInc/animated-bottom-navigation-bar-flutter/assets/38342480/bf7f01ad-21f2-4c30-87d5-3875042eba5d

While Implementing animated_notch_bottom_bar with ListView I have Face Some Scrolling Issues . can you help me to solve this issue?

**Comment by vizhan-lanars** [comment]
It looks like it is not connected to the package.
