### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by Samson11** [LanarsInc/animated-bottom-navigation-bar-flutter#8]
How do i show badges on the icons

**Comment by vizhan-lanars** [comment]
Did you try to implement it with `AnimatedBottomNavigationBar.builder`?

**Comment by Samson11** [comment]
No.

Just in case please could you give me en example of it.

**Comment by vizhan-lanars** [comment]
There is an [example](https://pub.dev/packages/animated_bottom_navigation_bar/example)  of how to use `AnimatedBottomNavigationBar.builder`

**Comment by Samson11** [comment]
Thanks alot
