### ISSUE TITLE
How about a running loading indicator in the edge of the navigation bar 

### ISSUE THREAD

**Issue by Shiba-Kar** [LanarsInc/animated-bottom-navigation-bar-flutter#80]
![untitled-ezgif com-resize](https://github.com/LanarsInc/animated-bottom-navigation-bar-flutter/assets/24454722/f40c51e6-8a8e-454d-8f93-96d7a0075c07)

**Comment by vizhan-lanars** [comment]
Hi.
No, it is out of plugin responsibility
