### ISSUE TITLE
Background color of the notchSmoothness is not able to be transparent

### ISSUE THREAD

**Issue by Adsoftwares1** [LanarsInc/animated-bottom-navigation-bar-flutter#85]
Hello, I tried 2 hours to chenge the background color of the notchSmoothness to make it tranparent that my content behind could be visible to the users, yes it takes any other color like red, green and others, but does not take transparent. screenshot is attached:

![WhatsApp Image 2024-09-09 at 11 18 06 AM](https://github.com/user-attachments/assets/64935dbc-fb90-43cc-ac88-b85951ab4aba)

**Comment by vizhan-lanars** [comment]
Try a solution from an https://github.com/LanarsInc/animated-bottom-navigation-bar-flutter/issues/52

**Comment by Adsoftwares1** [comment]
Thanks dear, you are great
